### PR TITLE
AMD globals

### LINKED ISSUE #11: Undefined identifier "define".
When targeting an AMD environment this is a spurious warning, it'd be nice to be able to hide it in those cases

### PR DESCRIPTION
**Pull request by lekkas**
Closes #11

### CODE REVIEW

**Comment by lekkas** [comment]
@Page- `resin-lint` is not smart enough to detect a project's environment and be aware of the respective globals. For this reason -and to also avoid having separate `coffeelint.json`'s per project to suppress warnings- we've included the most common environments used in Resin.io projects [here](https://github.com/resin-io/resin-lint/blob/master/config/coffeelint.json#L106) .

So in order to suppress warnings for undefined `define` in AMD, I've included 'amd' in the list of environments to import globals from.

**Comment by Page-** [comment]
Yeah, I didn't mean that we should detect it (although it'd be awesome if we could), just that we should allow it.

**Comment by Page-** [comment]
LGTM

**Comment by lekkas** [comment]
Published in `resin-lint@1.4.0`

**Pull request merged**
